# Generated by Django 3.0.7 on 2020-07-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200708_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincourse',
            name='image',
            field=models.ImageField(blank=True, upload_to='photo/', verbose_name='Фото'),
        ),
    ]
