# Generated by Django 3.0.7 on 2020-07-05 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_remove_allergen_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maincourse',
            name='created',
        ),
        migrations.RemoveField(
            model_name='maincourse',
            name='updated',
        ),
    ]
