# Generated by Django 3.0.7 on 2020-07-05 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20200705_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincourse',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Category'),
        ),
    ]
